### PR TITLE
Compose: inject sampledata as submodule

### LINKED ISSUE #15: Problem: make bootstrap fails trying to write to an existing directory
How to reproduce:
- Run `make bootstrap` twice
- You'll see the following error:

```
docker-compose exec --user root archivematica-storage-service \
	git clone https://github.com/artefactual/archivematica-sampledata.git \
	/home/archivematica/archivematica-sampledata
fatal: destination path '/home/archivematica/archivematica-sampledata' already exists and is not an empty directory.
make: *** [Makefile:27: bootstrap-storage-service] Error 128
```

The sampledata repo should be part of `src/` and tracked as a submodule, then shared with the containers using volumes.

### PR DESCRIPTION
**Pull request by sevein**
This closes #15 and #30.

### CODE REVIEW

**Comment by ross-spencer** [comment]
@sevein @jrwdunham just taking a look at this CR

**Comment by ross-spencer** [comment]
@sevein Changes look good - and importantly - work. 

Once merged, I think we will still have a storage-service/dashboard issue, I am seeing the following following `make bootstrap`:

```archivematica-dashboard_1        | DEBUG     2017-12-15 16:21:33  archivematica.common:storageService:get_location:168:  Storage locations returned: []```

Can discuss in a separate channel once I've done a bit more debug.

**Comment by ross-spencer** [comment]
@mamedin @sevein have we anyone else on a different environment can give the make bootstrap a whirl?

**Comment by sevein** [comment]
9d12342 in `master`

**Comment by jrwdunham** [comment]
I looked at this too. One thing that confused me a bit was that one can add dirs to /tmp/ss-location-data/archivematica/archivematica-sampledata/ on the host and they will not show up in the container. You must add dirs to /tmp/ss-location-data/archivematica/ or ./src/archivematica-sampledata/ if you want to see them in the transfer browser.

**Pull request merged**
