### PR TITLE
Enable indexless (headless) deploy

### PR DESCRIPTION
**Pull request by jrwdunham**
Moves all of the Elasticsearch configuration to a docker-compose.override.yml file. This file will be used by default when no config file is specified and will override the defaults in the docker-compose.yml file. If the latter file is explicitly referenced (`-f docker-compose.yml`) then only that config will be used and no Elasticsearch container will be built and search will be disabled in Archivematica. To see the config that will be used run in either case, run `docker-compose -f docker-compose.yml config` or `docker-compose config`.

Also fixes the environment variables that control whether search is enabled.

Note: DISCUSSION REQUESTED here:

- This PR increases the complexity of the docker-compose configuration and may not be worth that added complexity. The same result can be achieved by leaving the docker-compose config as is and instructing the user to manually stop and remove the Elasticsearch container.

### CODE REVIEW

**Comment by jrwdunham** [comment]
See https://docs.docker.com/compose/extends/

**Comment by jhsimpson** [comment]
This seems to be a reasonable approach - the link you provided to the docker docs is helpful.  

I haven't tested, but from reviewing the code and the linked docs, I vote :+1:  to merge this as is.

**Comment by jhsimpson** [comment]
@mamedin do you have any thoughts about this approach?

**Comment by mamedin** [comment]
I tried running on AM qa/1.x and SS qa/0.x (default .gitmodules):

```
  $ git clone https://github.com/artefactual-labs/am.git
  $ cd am
  $ git submodule update --init --recursive
  $ cd compose
  $ make create-volumes
  $ docker-compose -f docker-compose.yml up -d --build --remove-orphans
  $ make bootstrap
  $ make restart-am-services
```

I checked The SEARCH_ENABLED env variables are set to false in running containers:

```
maml@cabesa:~/artefactual/AM/am/compose$ docker-compose exec --user root archivematica-dashboard sh -c "env | grep SEARCH"
ARCHIVEMATICA_DASHBOARD_DASHBOARD_SEARCH_ENABLED=false
```

```
maml@cabesa:~/artefactual/AM/am/compose$ docker-compose exec --user root archivematica-mcp-server sh -c "env | grep SEARCH"
ARCHIVEMATICA_MCPSERVER_MCPSERVER_SEARCH_ENABLED=false
```

```
maml@cabesa:~/artefactual/AM/am/compose$ docker-compose exec --user root archivematica-mcp-client sh -c "env | grep SEARCH"
ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_SEARCH_ENABLED=false
```

But I can see the 'Archival Storage' and 'Backlog' tabs in the dashboard, and the following Elasticsearch error when using 'Archival Storage':

```
maml@cabesa:~/artefactual/AM/am/compose$ docker-compose logs archivematica-dashboard 2>&1 | tail -n 20
archivematica-dashboard_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
archivematica-dashboard_1        |   File "/src/dashboard/src/components/archival_storage/views.py", line 54, in overview
archivematica-dashboard_1        |     return list_display(request)
archivematica-dashboard_1        |   File "/src/dashboard/src/components/archival_storage/views.py", line 442, in list_display
archivematica-dashboard_1        |     es_client = elasticSearchFunctions.get_client()
archivematica-dashboard_1        |   File "/src/archivematicaCommon/lib/elasticSearchFunctions.py", line 155, in get_client
archivematica-dashboard_1        |     create_indexes_if_needed(_es_client)  # TODO: find a better place!
archivematica-dashboard_1        |   File "/src/archivematicaCommon/lib/elasticSearchFunctions.py", line 200, in create_indexes_if_needed
archivematica-dashboard_1        |     create_index(client, 'aips')
archivematica-dashboard_1        |   File "/src/archivematicaCommon/lib/elasticSearchFunctions.py", line 263, in create_index
archivematica-dashboard_1        |     response = client.indices.create(index, ignore=400)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
archivematica-dashboard_1        |     return func(*args, params=params, **kwargs)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 103, in create
archivematica-dashboard_1        |     params=params, body=body)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
archivematica-dashboard_1        |     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
archivematica-dashboard_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 89, in perform_request
archivematica-dashboard_1        |     raise ConnectionError('N/A', str(e), e)
archivematica-dashboard_1        | ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3ff16f5b50>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f3ff16f5b50>: Failed to establish a new connection: [Errno 111] Connection refused)
```

Another thing I have seen is that the Elasticsearch container is being created in the `make bootstrap` when the containers are built with the  `--remove-orphans` option:

```
Starting compose_mysql_1 ... done
User found.
User updated.
API key updated.
# SS needs to be restarted so the local space is created.
# See #303 (https://git.io/vNKlM) for more details.
docker-compose restart archivematica-storage-service
Restarting compose_archivematica-storage-service_1 ... done
docker-compose exec mysql mysql -hlocalhost -uroot -p12345 -e "\
	DROP DATABASE IF EXISTS MCP; \
	CREATE DATABASE MCP; \
	GRANT ALL ON MCP.* TO 'archivematica'@'%' IDENTIFIED BY 'demo';"
Warning: Using a password on the command line interface can be insecure.
docker-compose run \
	--rm \
	--entrypoint /src/dashboard/src/manage.py \
		archivematica-dashboard \
			migrate --noinput
Creating compose_elasticsearch_1 ...
```

I will try again during this afternoon in case I have not deployed correctly.

**Comment by mamedin** [comment]
I tested again, and it worked. 

The archivematica source directory needed a checkout to a recent version. I have tested with AM `stable/1.7.x` and it works perfectly. 

The minimum version of AM that includes the option to run without Elasticsearch could be included in the README file.

I've seen again that the Elasticsearch container is created in the `make bootstrap` with the `--remove-orphans` option

**Comment by sevein** [comment]
> The same result can be achieved by leaving the docker-compose config as is and instructing the user to manually stop and remove the Elasticsearch container.

I'd much prefer that! I've worked in a different project with lots of compose yml files and overrides and it's definitely not something I enjoyed.

This PR achieves two things:
1. Not running Elasticsearch when it's not needed.
2. Making easy to deploy in headless mode.

For a developer, 1) should not be a problem because we do it most of the time anyways and 2) is just one of many configuration permutations we have in Archivematica so I'd rather avoid custom solutions, I think it's up to the developer to tweak as needed.

**Pull request closed without merging**
